### ISSUE TITLE
No invitation for courses in single activity format

### ISSUE THREAD

**Issue by ralf-krause** [grabs/moodle-local_invitation#1]
We found that you can't set an invitation if you set the course format to "single activity format". 

The workaround is to set the topic format with no topic so users only can see the topic 0. But the users have to take two steps: go into the course and then open the activity. Please repair this issue. The invitation is a very nice plugin! We like it!

Ralf Krause
moodleSCHULE e.V.

**Comment by grabs** [comment]
Hi Ralf,
thank you very much for pointing this out.
I am currently working on this and release it in the next few days.
Best regards
Andreas

**Comment by grabs** [comment]
Hi Ralf,
I have published the fixed version in the moodle plugin database.
Best regards
Andreas

**Comment by ralf-krause** [comment]
Hi Andreas,
thank you very much for your support. I just installed the invitation plugin in our Bildungsportal. We are testing the plugin with BigBlueButton. We want to invite people for video conferences who do not have an account. 

The screenshot shows the BigBlueButton activity page. I am teacher in this course. There is no editor to setup or edit the invitation on the activity page. I find the editor for the invitation when I open the participants sub page but I don‘t getimt on the course main page which is the activity page in a single activity course. We are using Moodle 3.11.5+.

Yes, I know that we should use a better BigBlueButton server … we are currently testing some different servers because the networks in some schools and in the school administration office are not open for BigBlueButton.

Ralf

![5D1B7062-7002-4930-BBC6-0A5A7AC4E313](https://user-images.githubusercontent.com/27956839/153707423-d8bddac2-c457-4079-846b-7c21b8ae94e7.jpeg)

**Comment by grabs** [comment]
Hi Ralf,
sorry, I did a wrong check with an empty folder resource. I didn't use the single activity at all.
Now it should work as expected. The new release is published in the moodle database.
Best regards
Andreas

**Comment by ralf-krause** [comment]
Great! 
Thank you very much for the nice plugin and your great support.

![73340B2E-90EB-4FAB-AFA5-C3896E46EAEF](https://user-images.githubusercontent.com/27956839/153713250-ada84670-b4aa-4bd0-aea5-b059db3f7bf3.jpeg)
